### ISSUE TITLE
MAT file type specification

### ISSUE THREAD

**Issue by lukacupic** [smlu/gimp-ijim#1]
Hi,

I was wondering if you could give some information on the structure of the MAT file type. I know everything is written in the code, but it would be helpful to have a clear human-readable specification in one place, similar to this:
http://www.watto.org/specs.html?specs=Archive_GOB_GOB_2

Thanks!

**Comment by smlu** [comment]
Hey,
the MAT file of the Indiana Jones and the Infernal Machine game is in essence a container file of 1 or more uncompressed [mipmap](https://en.wikipedia.org/wiki/Mipmap) cel images (cel - short for celluloid). The structure of file is very similar to [MAT](http://www.jkhub.net/library/index.php?title=Reference:Material) files found in other games based on [Sith Engine](https://starwars.fandom.com/wiki/Sith_Engine).

Basic file layout:
  ```
Offset          Struct
-----------------------
  0x00            Header - 76 bytes
  0x4C            List of Records - 40 bytes * number of mipmap cels - not used by engine
  <variable>      List of Mipmap Cel Images - (24 bytes  header + mipmap pixel data) * number of mipmap cels
```

Structs definition:
(Each number on the left side represents number of bytes)
```
HEADER - 76 bytes
  4 - magic   = "MAT " (0x4D415420)
  4 - version = 0x32
  4 - type    = 2 (mipmap RGB[A] texture)
  4 - number of records (must be the same as number of cels)
  4 - number of cel images

  // Color format - pixel encoding of every image in mipmap (separate structure)
  // e.g.: RGB565, RGBA4444, RGB888, RGBA8888 etc...
    4 - color mode - RGB = 1, RGBA = 2
    4 - bits per pixel (BPP)
    
    4 - BPP of red color component
    4 - BPP of green color component
    4 - BPP of blue color component
    
    /// Color mask for RGB color components
    4 - left shift for red color component
    4 - left shift for green color component
    4 - left shift for green color component

    4 - right shift for red color component
    4 - right shift for green color component
    4 - right shift for green color component

    // Alpha color component info
    4 - BPP
    4 - left shift
    4 - right shift 

RECORD  - 40 bytes
  4 - type          =  8 - texture
  4 - unknown
  4 - unknown
  4 - unknown
  4 - unknown
  4 - unknown
  4 - unknown
  4 - unknown
  4 - unknown
  4 - cel idx     - index in cel list  

MIPMAP CEL IMAGE
  HEADER - 24 bytes
    4 - width   - width of top mipmap image at LOD 0
    4 - height  - height of top mipmap image at LOD 0
    4 - unknown / alignment padding? - not used
    4 - unknown / alignment padding? - not used
    4 - unknown / alignment padding? - not used
    4 - numper of mipmap levels
  MIPMAP PIXEL DATA - the size of pixel data has to be calculated
```

Function to calculate the size of mipmap pixel data:
```
uint4 calcMipmapSize(uint4 width, uint4 height, uint4 mipLevels, ColorFormat cf)
{
  uint4 size = 0;
  while (mipLevels --> 0 && width && height)
  {
    size  += width * height * (cf.bpp /8)
    width  = width  /2;
    height = height /2;
  }
  return size;
}
```

Implementation of the above structures: [C++](https://github.com/smlu/ProjectMarduk/blob/85de7ac497be5587801f9734e4c4478260db0ee1/libraries/libim/content/asset/material/impl/serialization/mat_structs.h), [Python 2](https://github.com/smlu/gimp-ijim/blob/2dc691bc987a4a87a3079eeb4590c89ec4ea8096/file-mat/mat.py#L91-L146), [Python 3](https://github.com/smlu/blender-ijim/blob/a67f90f7486847f357e0c12225512ebcd6d363e1/ijim/material/material.py#L10-L71) 
and reading MAT file: [C++](https://github.com/smlu/ProjectMarduk/blob/85de7ac497be5587801f9734e4c4478260db0ee1/libraries/libim/content/asset/material/impl/serialization/mat.cpp#L42-L85), [Python 2](https://github.com/smlu/gimp-ijim/blob/2dc691bc987a4a87a3079eeb4590c89ec4ea8096/file-mat/mat.py#L168-L344), [Python 3](https://github.com/smlu/blender-ijim/blob/a67f90f7486847f357e0c12225512ebcd6d363e1/ijim/material/material.py#L78-L163)

I hope this helps.

**Comment by lukacupic** [comment]
I highly appreciate your effort, thank you so much.
